services:
    filelib.twig.extension:
        class: Xi\Bundle\FilelibBundle\Twig\Extension\FilelibExtension
        arguments: [ @filelib, @filelib.renderer ]
        tags:
            -  { name: twig.extension }
