language: php

php:
  - 5.4
  - 5.5

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --dev

script: phpunit -c Tests

notifications:
  irc: "irc.freenode.net#xi-project"
